package:
  name: cyclus
  version: 1.2.0

source:
  fn: 1.2.0.tar.gz # [linux and __import__('os').getenv('NMI_PLATFORM')]
  url: https://github.com/cyclus/cyclus/archive/1.2.0.tar.gz # [linux and __import__('os').getenv('NMI_PLATFORM')]
  git_url: https://github.com/cyclus/cyclus.git # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]
  git_tag: 1.2.0 # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]

requirements:
   build:
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
   run:
    - sigcpp
    - glibmm
    - libxmlpp
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]

about:
  home: Cyclus
  license: BSD Clause 3
