package:
  name: cycamore
  version: 1.2.0

source:
  fn: 1.2.0.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  url: https://github.com/cyclus/cycamore/archive/1.2.0.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  git_url: https://github.com/cyclus/cycamore.git # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]
  git_tag: 1.2.0 # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]

requirements:
   build:
    - cyclus
    - cmake
    - python
   run:
    - cyclus

about:
  home: Cyclus
  license: BSD 3 Clause
